version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.11.1
    - 3.9.0
    - 3.9.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.4.0
  - dependency-name: vue-i18n
    versions:
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.2
    - 8.24.3
    - 9.1.5
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
    - 7.9.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.24.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.4
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@vue/cli-plugin-unit-jest"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-vuex"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.12
  - dependency-name: sass-loader
    versions:
    - 11.0.1
